version: "3"
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: avblink/jenkins
    container_name: jenkins
    hostname: jenkins
    restart: always
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./volumes/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock